### ISSUE TITLE
[ASK] Log - Kenapa tidak menggunakan log singleton (global)

### ISSUE THREAD

**Issue by aryayunanta-ralali** [khannedy/golang-clean-architecture#5]
Selamat siang pak @khannedy , saya mau nanya terkait log. Kenapa menggunakan log sebagai dependency dan tidak menggunakan singleton saja ? Thanks

**Comment by khannedy** [comment]
jika ingin menggunakan logger berbeda untuk tiap jenis object / layer, jadi tinggal gunakan object logger yang berbeda
