### ISSUE TITLE
[ASK] Folder Controller

### ISSUE THREAD

**Issue by lutfiandri** [khannedy/golang-clean-architecture#7]
Untuk controller kenapa tidak ada folder controller tersendiri ya pak seperti `internal > delivery > http > controller`? Kenapa hanya di `internal > delivery > http`? Sementara itu di folder `http` sendiri masih ada subdirectory untuk `middleware` dan `route`.

**Comment by khannedy** [comment]
silahkan saja jika ingin dibuat folder controller
