### ISSUE TITLE
[ASK] Tidak ada unit test

### ISSUE THREAD

**Issue by lutfiandri** [khannedy/golang-clean-architecture#8]
1. Jika ingin menambahkan unit test bisa ditaruh mana ya pak biar enak bacanya? 

2. Karena tiap file (seperti usecase dan repository) tidak ada interfacenya, apakah sebaiknya perlu menambahkan interface untuk menulis unit testnya?

Thanks before atas jawabannya

**Comment by khannedy** [comment]
1. unit test, ditaruh di folder lokasi tempat file yang akan di test

2. tidak wajib membuat interface di golang, apalagi jika kita tau hanya 1 implementasi, silahkan baca https://100go.co/5-interface-pollution/
